In [121]:
import pandas as pd 
import numpy as np 
import seaborn as sns
import matplotlib.pyplot as plt 
import os

In [122]:
for dirname ,_, filenames in os.walk('c:/Users/Sandeep/Documents/'):
    for filename in filenames :
        if filename.endswith('csv'):
            print(os.path.join(dirname,filename))

c:/Users/Sandeep/Documents/netflix_titles.csv

In [123]:
df = pd.read_csv('c:/Users/Sandeep/Downloads/ecommerce_data_science_practice.csv')
df.head(1)

,daTransaction_ID,Timestamp,User_ID,City,Product_Category,Price_Per_Unit,Quantity,Payment_Method,Coupon_Applied,Total_Amount,Is_Repeat_Customer
0,TXN_100000,2026-04-13 19:28:00,USR_5815,Delhi,Electronics,11656.0,2,Cash on Delivery,1,23312.0,0

In [124]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   daTransaction_ID    2500 non-null   object
 1   Timestamp           2500 non-null   object
 2   User_ID             2500 non-null   object
 3   City                2460 non-null   object
 4   Product_Category    2500 non-null   object
 5   Price_Per_Unit      2441 non-null   float64
 6   Quantity            2500 non-null   int64
 7   Payment_Method      2465 non-null   object
 8   Coupon_Applied      2500 non-null   int64
 9   Total_Amount        2441 non-null   float64
 10  Is_Repeat_Customer  2500 non-null   int64
dtypes: float64(2), int64(3), object(6)
memory usage: 215.0+ KB

In [125]:
df.shape

(2500, 11)

In [126]:
df.isnull().sum()

daTransaction_ID       0
Timestamp              0
User_ID                0
City                  40
Product_Category       0
Price_Per_Unit        59
Quantity               0
Payment_Method        35
Coupon_Applied         0
Total_Amount          59
Is_Repeat_Customer     0
dtype: int64

In [127]:
df = df.drop_duplicates() 
price = df['Price_Per_Unit'].median()
df['Price_Per_Unit'] = df['Price_Per_Unit'].fillna(price)
df['Total_Amount'] = df['Price_Per_Unit'] * df['Quantity']
df = df.fillna({'City':'unknown', 'Payment_Method':'unknown Payment_Method'})
df.isnull().sum()

daTransaction_ID      0
Timestamp             0
User_ID               0
City                  0
Product_Category      0
Price_Per_Unit        0
Quantity              0
Payment_Method        0
Coupon_Applied        0
Total_Amount          0
Is_Repeat_Customer    0
dtype: int64

In [128]:
df = df.apply(
    lambda x : x.astype(str).str.lower().str.strip().str.replace(' ','_') 
    if x.dtype == 'object' 
    else x 
    )

df.columns = df.columns.str.lower().str.strip().str.replace(' ','_')

df.head(2)

,datransaction_id,timestamp,user_id,city,product_category,price_per_unit,quantity,payment_method,coupon_applied,total_amount,is_repeat_customer
0,txn_100000,2026-04-13_19:28:00,usr_5815,delhi,electronics,11656.0,2,cash_on_delivery,1,23312.0,0
1,txn_100001,2026-01-15_10:07:00,usr_5442,hyderabad,home_appliances,24118.0,1,debit_card,0,24118.0,1

In [129]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2500 entries, 0 to 2499
Data columns (total 11 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   datransaction_id    2500 non-null   object
 1   timestamp           2500 non-null   object
 2   user_id             2500 non-null   object
 3   city                2500 non-null   object
 4   product_category    2500 non-null   object
 5   price_per_unit      2500 non-null   float64
 6   quantity            2500 non-null   int64
 7   payment_method      2500 non-null   object
 8   coupon_applied      2500 non-null   int64
 9   total_amount        2500 non-null   float64
 10  is_repeat_customer  2500 non-null   int64
dtypes: float64(2), int64(3), object(6)
memory usage: 215.0+ KB